baseURL = 'https://tapmapapp.org/'
languageCode = 'en-us'
title = 'Tap Map'
theme = 'ananke'
defaultContentLanguage = "en-us"

[params]
    buildYear = 2025
    background_color_class = "bg-custom"

[languages]
  [languages.en-US]
    contentDir = 'content/en-US'
    weight = 10
      [languages.en-US.params]
        languageName = '🇺🇸'
  [languages.en-GB]
    contentDir = 'content/en-GB'
    weight = 20
      [languages.en-GB.params]
        languageName = '🇬🇧'
  [languages.fr-FR]
    contentDir = 'content/fr-FR'
    weight = 30
      [languages.fr-FR.params]
        languageName = '🇫🇷'



[[languages.en-US.menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[languages.en-GB.menu.main]]
  identifier = "home"
  name = "Home"
  url = "/en-GB"
  weight = 1

[[languages.fr-FR.menu.main]]
  identifier = "home"
  name = "Acceuil"
  url = "/fr-FR"
  weight = 1

[[languages.en-US.menu.main]]
  identifier = "faq"
  name = "FAQ"
  url = "/faq"
  weight = 2

[[languages.en-GB.menu.main]]
  identifier = "faq"
  name = "FAQ"
  url = "/en-GB/faq"
  weight = 2

[[languages.fr-FR.menu.main]]
  identifier = "faq"
  name = "FAQ"
  url = "/fr-FR/FAQ"
  weight = 2


[[languages.en-US.menu.main]]
  identifier = "support"
  name = "Support"
  url = "/support"
  weight = 3

[[languages.en-GB.menu.main]]
  identifier = "support"
  name = "Support"
  url = "/en-GB/support"
  weight = 3

[[languages.fr-FR.menu.main]]
  identifier = "support"
  name = "Assistance"
  url = "/fr-FR/support"
  weight = 3

[[languages.en-US.menu.main]]
  identifier = "privacy"
  name = "Privacy"
  url = "/privacy"
  weight = 4

[[languages.en-GB.menu.main]]
  identifier = "privacy"
  name = "Privacy"
  url = "/en-GB/privacy/"
  weight = 4

[[languages.fr-FR.menu.main]]
  identifier = "privacy"
  name = "Confidentialité"
  url = "/fr-fr/privacy"
  weight = 4

[[languages.en-US.menu.main]]
  identifier = "eula"
  name = "EULA"
  url = "/eula"
  weight = 5

[[languages.en-GB.menu.main]]
  identifier = "eula"
  name = "EULA"
  url = "/en-GB/eula"
  weight = 5

[[languages.fr-FR.menu.main]]
  identifier = "eula"
  name = "CLUF"
  url = "/fr-FR/eula"
  weight = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true